---
host_ansible_ssh_host: cbay02.thecshore.ca
host_ansible_ssh_port: "{{ vault_host_ansible_ssh_port }}"
host_email_interfaces: "{{ vault_host_email_interfaces }}"
host_email_relayhost: "{{ vault_host_email_relayhost }}"
host_email_tls_verify_match: "{{ vault_host_email_tls_verify_match }}"
host_local_ipv6_addr: "{{ vault_host_local_ipv6_addr }}"
host_local_ipv6_gateway: "{{ vault_host_local_ipv6_gateway }}"
host_local_ipv6_prefix: "{{ vault_host_local_ipv6_prefix }}"
host_private_client_cert_cert_content: "{{ vault_private_client_cert_cert_content }}"
host_private_client_cert_cert_file: "{{ vault_private_client_cert_cert_file }}"
host_private_client_cert_key_content: "{{ vault_private_client_cert_key_content }}"
host_private_client_cert_key_file: "{{ vault_private_client_cert_key_file }}"
host_vbridge: "{{ vault_vbridge }}"
...
