---
all:
  children:
    backup_clients:
      hosts: {}
    bare_metal:
      children:
        libvirtd_hosts:
          children:
            ldev_host:
              hosts:
                dlcicl01.ldev.thecshore.ca:
            kss_host: {}
            # cbay02.kss.thecshore.ca:
    cert_private:
      children:
        ssl_private_clients:
          hosts:
            dlcicl01.ldev.thecshore.ca:
            airlockldev.ldev:
            gateldev.ldev:
            gdavldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
            wwwldev.ldev:
        ssl_private_servers:
          hosts:
            gdavldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
            wwwldev.ldev:
    cert_public:
      children:
        public_full:
          # Uses a combined chain+cert+key file
          hosts:
            gateldev.ldev:
        ssl_public_servers:
          hosts:
            gateldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
    edge_hosts:
      children:
        bastions:
          hosts:
            airlockldev.ldev:
        external_services:
          hosts:
            imapldev.ldev:
            smtp01ldev.ldev:
        external_ssh:
          hosts:
            airlockldev.ldev:
            dlcicl01.ldev.thecshore.ca:
        rproxy_external:
          hosts:
            gateldev.ldev:
    email_mxes:
      children:
        external_mxes:
          hosts:
            smtp01ldev.ldev:
        internal_mxes:
          hosts:
            imapldev.ldev:
    email_senders:
      children:
        email_external_senders:
          hosts:
            smtp01ldev.ldev:
        email_internal_senders:
          hosts:
            dlcicl01.ldev.thecshore.ca:
            airlockldev.ldev:
            gateldev.ldev:
            gdavldev.ldev:
            imapldev.ldev:
            wwwldev.ldev:
    environments:
      children:
        bare_metal_local:
          hosts:
            dlcicl01.ldev.thecshore.ca:
            # bare_metal_rbxks:
            #  hosts:
            #     cbay02.kss.thecshore.ca:
        ldev:
          hosts:
            airlockldev.ldev:
            gateldev.ldev:
            gdavldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
            wwwldev.ldev:
            # kss:
            #   hosts:
            #     airlockkss.kss:
            #     gatekss.kss:
            #     gdavkss.kss:
            #     imapkss.kss:
            #     smtp01kss.kss:
            #     wwwkss.kss:
    groupware:
      hosts:
        gdavldev.ldev:
    host_locations:
      children:
        dfd_local:
          hosts:
            dlcicl01.ldev.thecshore.ca:
        ovh_bhs:
          hosts: {}
        ovh_rbx:
          hosts: {}
    mailbox_servers:
      hosts:
        imapldev.ldev:
    rproxy_internal:
      hosts:
        gdavldev.ldev:
    website_servers:
      hosts:
        wwwldev.ldev:
...
