---
all:
  children:
    backup_clients:
      hosts: {}
    bare_metal:
      children:
        libvirtd_hosts:
          children:
            kss_host:
              hosts:
                cbay02.thecshore.ca:
    cert_private:
      children:
        ssl_private_clients:
          hosts:
            cbay02.thecshore.ca:
            airlockkss.kss:
            gatekss.kss:
            gdavkss.kss:
            imapkss.kss:
            smtp01kss.kss:
            wwwkss.kss:
        ssl_private_servers:
          hosts:
            gdavkss.kss:
            imapkss.kss:
            smtp01kss.kss:
            wwwkss.kss:
    cert_public:
      children:
        public_full:
          # Uses a combined chain+cert+key file
          hosts:
            gatekss.kss:
        ssl_public_servers:
          hosts:
            gatekss.kss:
            imapkss.kss:
            smtp01kss.kss:
    edge_hosts:
      children:
        bastions:
          hosts:
            airlockkss.kss:
        external_services:
          hosts:
            imapkss.kss:
            smtp01kss.kss:
        external_ssh:
          hosts:
            airlockkss.kss:
            cbay02.thecshore.ca:
        rproxy_external:
          hosts:
            gatekss.kss:
    email_mxes:
      children:
        external_mxes:
          hosts:
            smtp01kss.kss:
        internal_mxes:
          hosts:
            imapkss.kss:
    email_senders:
      children:
        email_external_senders:
          hosts:
            smtp01kss.kss:
        email_internal_senders:
          hosts:
            cbay02.thecshore.ca:
            airlockkss.kss:
            gatekss.kss:
            gdavkss.kss:
            imapkss.kss:
            wwwkss.kss:
    environments:
      children:
        bare_metal_rbxks:
          hosts:
            cbay02.thecshore.ca:
        kss:
          hosts:
            airlockkss.kss:
            gatekss.kss:
            gdavkss.kss:
            imapkss.kss:
            smtp01kss.kss:
            wwwkss.kss:
    groupware:
      hosts:
        gdavkss.kss:
    host_locations:
      children:
        dfd_local:
          hosts: {}
        ovh_bhs:
          hosts: {}
        ovh_rbx:
          hosts:
            airlockkss.kss:
            cbay02.thecshore.ca:
            gatekss.kss:
            gdavkss.kss:
            imapkss.kss:
            smtp01kss.kss:
            wwwkss.kss:
    mailbox_servers:
      hosts:
        imapkss.kss:
    rproxy_internal:
      hosts:
        gdavkss.kss:
    website_servers:
      hosts:
        wwwkss.kss:
...
