---
- name: Gather facts for common instance plays
  hosts: all
  gather_facts: true
  tasks:
  - name: Ensure facts gathered
    ansible.builtin.setup:

- name: Configure internal email senders
  hosts: email_internal_senders:!internal_mxes:!external_mxes
  roles:
  - system_postfix_sender_internal
...
