---
- name: Wait for cloud init to finish
  hosts: all
  tasks:
  - name: Check cloud init status
    community.general.cloud_init_data_facts:
      filter: status
    register: cistat
    until: cistat.cloud_init_data_facts.status.v1.stage is defined and not cistat.cloud_init_data_facts.status.v1.stage
    retries: 50
    delay: 5
  - name: Ensure cloud init result was success
    community.general.cloud_init_data_facts:
      filter: status
    register: res
    failed_when: res.cloud_init_data_facts.status.v1.errors is defined and res.cloud_init_data_facts.status.v1.errors
    changed_when: false

- name: For all hosts add a password to admin user and set fqdn/hostname aliases
  hosts: all
  gather_facts: true
  roles:
  - danielfdickinson.system_base_debian.user_admin
  - danielfdickinson.system_base_debian.network_hosts_file
  vars:
    new_base_homedir: "{{ admin_base_homedir }}"
    new_admin_password: "{{ admin_password }}"
    new_admin_ssh_key: "{{ admin_ssh_key }}"
    new_admin_user: "{{ admin_user }}"

- name: Except bastions, install base packages and firmware, and reboot guests
  hosts: all:!libvirtd_hosts:!bastions
  # Avoid connectivity issues by not rebooting vm host or bastion
  roles:
  - danielfdickinson.system_base_debian.dfd_base_misc
  - danielfdickinson.system_base_debian.ufw
  - danielfdickinson.system_base_debian.firmware_install

- name: Configure OVH (BHS) clients for backups
  hosts: backup_clients:&ovh_bhs
  roles:
  - backup_ovh
  - backup_restic

- name: Configure backups on all guests and bare-metal hosts were we can
  hosts: backup_clients
  roles:
  - backup_restic
...
