---
- name: Gather facts for mail servers
  hosts: all
  gather_facts: true
  tasks:
  - name: Ensure facts gathered
    ansible.builtin.setup:

- name: Configure IMAP (mailbox) servers
  hosts: mailbox_servers
  roles:
  - service_dovecot
- name: Configure external MXes
  hosts: external_mxes
  roles:
  - service_postfix_mx_external
...
