---
- name: Gather facts for web servers and reverse proxy
  hosts: all
  gather_facts: true
  tasks:
  - name: Ensure facts gathered
    ansible.builtin.setup:

- name: Configure website servers (including limited rsyncd for site deploys)
  hosts: website_servers
  roles:
  - service_webhost_static

- name: Configure groupware
  hosts: groupware
  roles:
  - service_sogo

- name: Configure external (edge) reverse proxy
  hosts: rproxy_external
  roles:
  - service_haproxy
...
