---
- name: Wait for cloud init to finish
  hosts: libvirtd_hosts:bastions
  tasks:
  - name: Check cloud init status
    community.general.cloud_init_data_facts:
      filter: status
    register: cistat
    until: cistat.cloud_init_data_facts.status.v1.stage is defined and not cistat.cloud_init_data_facts.status.v1.stage
    retries: 50
    delay: 5
  - name: Ensure cloud init result was success
    community.general.cloud_init_data_facts:
      filter: status
    register: res
    failed_when: res.cloud_init_data_facts.status.v1.errors is defined and res.cloud_init_data_facts.status.v1.errors
    changed_when: false

- name: Configure libvirtd hosts and bastions with base config
  hosts: libvirtd_hosts:bastions
  gather_facts: true
  roles:
  - danielfdickinson.system_base_debian.dfd_base_misc
  - danielfdickinson.system_base_debian.ufw
  - danielfdickinson.system_base_debian.fail2ban

- name: Configure bastions in order to access other guests
  hosts: bastions
  gather_facts: true
  roles:
  - user_bastion_user_add
  - danielfdickinson.system_base_debian.firmware_install
  tasks:
  - name: Ensure netcat-openbsd only for bastions (it's used for SSH proxy)
    become: yes
    ansible.builtin.apt:
      name:
      - netcat-openbsd
      state: present
...
