---
roles:
- name: maxhoesel.nut_netclient
  version: main

collections:
- name: ansible.utils
  version: 2.8.0
  source: "https://galaxy.ansible.com"
- name: community.general
  version: 6.1.0
  source: "https://galaxy.ansible.com"
- name: danielfdickinson.system_base_debian
  version: 0.2.0
  source: "https://github.com/danielfdickinson/system_base_debian"
  type: git
...
