---
dependencies:
- role: system_cert_ca_private
- role: system_cert_server_private
- role: packages_apache2
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure apache2 global settings
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
