---
- name: Prevent freshclam install from modifying our configuration
  become: yes
  ansible.builtin.copy:
    content: conf_force_conffold=YES
    dest: /etc/ucf.conf
    group: root
    mode: "0644"
    owner: root
- name: Ensure clamav directory exists
  become: yes
  ansible.builtin.file:
    path: /etc/clamav
    group: root
    mode: "0755"
    owner: root
    state: directory
- name: Ensure freshclam seed db directory exists
  become: yes
  ansible.builtin.file:
    path: /var/local/freshclam-seed-db
    group: root
    mode: "0755"
    owner: root
    state: directory
- name: Copy freshclam seed db files
  become: yes
  ansible.builtin.copy:
    dest: /var/local/freshclam-seed-db/
    group: root
    mode: "0755"
    owner: root
    src: "{{ local_freshclam_custom_url }}"
  when: local_freshclam_custom_url is defined
- name: Create freshclam configuration that uses private mirror
  # Note that use of a https://pypi.org/project/cvdupdate/ private
  # mirror is recommended during testing to avoid being rate limited.
  become: yes
  ansible.builtin.template:
    dest: /etc/clamav/freshclam.conf
    group: root
    mode: "0644"
    owner: root
    src: freshclam.conf.j2
- name: Ensure clamav-daemon is installed
  become: yes
  ansible.builtin.apt:
    name:
    - clamav-daemon
    - clamav-freshclam
...
