---
- name: Enable spamd
  become: yes
  ansible.builtin.systemd:
    name: spamassassin
    enabled: true
    state: started
- name: Configure spamass-milter startup
  become: yes
  ansible.builtin.copy:
    dest: /etc/default/spamass-milter
    group: root
    mode: "0644"
    owner: root
    src: spamass-milter.default
  notify: Restart spamass-milter
...
