---
admin_base_homedir: "{{ vault_admin_base_homedir }}"
admin_gecos: "{{ vault_admin_gecos }}"
admin_password: "{{ vault_admin_password }}"
admin_ssh_key: "{{ vault_admin_ssh_key }}"
admin_user: "{{ vault_admin_user }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_host: "{{ host_ansible_ssh_host | default(None) }}"
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
central_external_domain: "{{ vault_central_external_domain }}"
central_external_email: "{{ vault_central_external_email }}"
central_internal_domain: "{{ vault_central_internal_domain }}"
central_internal_email: "{{ vault_central_internal_email }}"
fallback_dns: "{{ vault_fallback_dns }}"
internal_relay_port: "{{ vault_internal_relay_port }}"
local_freshclam_mirror: "{{ vault_local_freshclam_mirror | default(None) }}"
mail_local_destinations: "{{ default_mail_local_destinations }}"
remote_admin_ip: "{{ vault_remote_admin_ip | default(None) }}"
remote_ignore_ips: "{{ remote_admin_ip }}{% if remote_monitoring_ips is defined %} {{ remote_monitoring_ips }}{% endif %}"
remote_monitoring_ips: "{{ vault_remote_monitoring_ips | default([]) }}"
v6natnet_ula: "{{ vault_v6natnet_ula | default(None) }}"
...
