---
admin_base_homedir: "{{ vault_admin_base_homedir }}"
admin_gecos: "{{ vault_admin_gecos }}"
admin_password: "{{ vault_admin_password }}"
admin_ssh_key: "{{ vault_admin_ssh_key }}"
admin_user: "{{ vault_admin_user }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_host: "{{ host_ansible_ssh_host | default(null) }}"
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
central_external_domain: "{{ vault_central_external_domain }}"
central_external_email: "{{ vault_central_external_email }}"
central_internal_domain: "{{ vault_central_internal_domain }}"
central_internal_email: "{{ vault_central_internal_email }}"
default_mail_local_destinations: "{{ vault_default_mail_local_destinations }}"
email_interfaces: "{{ vault_email_interfaces }}"
email_relayhost: "{{ host_email_relayhost | default('localhost') }}"
instance_v4address: "{{ ansible_facts['default_ipv4']['address'] }}"
instance_fqdn: "{{ ansible_facts['fqdn'] }}"
instance_hostname: "{{ ansible_facts['hostname'] }}"
internal_relay_port: "{{ vault_internal_relay_port }}"
local_ipv6_addr: "{{ host_local_ipv6_addr }}"
mail_local_destinations: "{{ default_mail_local_destinations }}"
private_ca_cert_certificate: "{{ vault_private_ca_cert_certificate }}"
private_ca_cert_file: "{{ vault_private_ca_cert_file }}"
private_client_cert_cert_content: "{{ host_private_client_cert_cert_content }}"
private_client_cert_cert_file: "{{ host_private_client_cert_cert_file }}"
private_client_cert_key_content: "{{ host_private_client_cert_key_content }}"
private_client_cert_key_file: "{{ host_private_client_cert_key_file }}"
private_client_cert_full_file: "{{ host_private_client_cert_cert_file | replace('-cert', '-full') | default(null) }}"
private_cert_content: "{{ host_private_client_content }}"
private_cert_cert_file: "{{ host_private_cert_cert_file }}"
private_cert_full_file: "{{ host_private_client_cert_full_file | replace('-cert', '-full') | default(null) }}"
private_cert_key_content: "{{ host_private_cert_key_content }}"
private_cert_key_file: "{{ host_private_cert_key_file }}"
public_cert_cert_file: "{{ host_public_cert_cert_file }}"
public_cert_cert_file_src: "{{ host_public_cert_cert_file_src }}"
public_cert_full_file: "{{ host_public_cert_full_file }}"
public_cert_key_file: "{{ host_public_cert_key_file }}"
public_cert_key_file_src: "{{ host_public_cert_key_file_src }}"
public_cert_key_private_key: "{{ host_public_cert_private_key }}"
remote_admin_ip: "{{ vault_remote_admin_ip | default(null) }}"
remote_ignore_ips: "{{ [remote_admin_ip, remote_monitoring_ips] | flatten | unique }}"
remote_monitoring_ips: "{{ vault_remote_monitoring_ips | default([]) }}"
v6natnet_ula: "{{ vault_v6natnet_ula | default(null) }}"
well_known_admin_aliases: "{{ vault_well_known_admin_aliases }}"
...
