---
dependencies:
- role: danielfdickinson.system_base_debian.fail2ban
  f2b_jails:
  - dest: mx
    port: smtp,{{ submission_relay_port }},{{ backupmx_port }}
- role: system_cert_server_private
- role: system_cert_public
- role: system_postfix_common
  vars:
    postfix_bkmx_incoming: true
    postfix_direct_delivery: true
    postfix_is_external_mx: true
    postfix_is_mx: true
    postfix_lmtp_uses_tls: true
    postfix_mta_local: false
    postfix_mua_incoming: true
    postfix_smtp_to_internal_mx: false
    postfix_uses_milters: true
    postfix_uses_policyd_spf: true
    postfix_virtual_mailboxes: "{{ mail_groupware_users }}"
- role: system_policyd_spf_python
- role: system_clamav_milter
- role: system_spamass_milter
- role: danielfdickinson.system_base_debian.ufw
  ufw_added_rules:
  - port: "{{ backupmx_port | string }}"
  - port: "{{ smtp_port | string }}"
  - from: "{{ v4nat_net }}/{{ v4nat_prefix }}"
    port: "{{ submission_relay_port | string }}"
  - from: "{{ v6nat_net }}/{{ v6nat_prefix }}"
    port: "{{ submission_relay_port | string }}"
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure postfix as external MX
  license: MIT
  min_ansible_version: 2.14.1
  platforms:
  - name: Debian
    versions:
    - all
...
