---
admin_base_homedir: "{{ vault_admin_base_homedir }}"
admin_gecos: "{{ vault_admin_gecos }}"
admin_password: "{{ vault_admin_password }}"
admin_ssh_key: "{{ vault_admin_ssh_key }}"
admin_user: "{{ vault_admin_user }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
ansible_ssh_common_args: "{% if 'external_ssh' not in group_names %}-o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -p {{ bastion_port }} -W %h:%p -q {{ bastion_user }}@{{ bastion_host }}\"{% endif %}"
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
backupmx_port: "{{ vault_backupmx_port }}"
bastion_host: "{{ vault_bastion_host }}"
bastion_port: "{{ vault_bastion_port }}"
bastion_ssh_key: "{{ vault_bastion_ssh_key }}"
bastion_user: "{{ vault_bastion_user }}"
central_external_domain: "{{ vault_central_external_domain }}"
central_external_email: "{{ vault_central_external_email }}"
central_internal_domain: "{{ vault_central_internal_domain }}"
central_internal_email: "{{ vault_central_internal_email }}"
default_mail_local_destinations: "{{ vault_default_mail_local_destinations }}"
email_interfaces: "{{ vault_email_interfaces }}"
email_relayhost: "{{ host_email_relayhost | default('imapldev.ldev') }}"
external_relayhost: "{{ vault_external_relayhost }}"
gdav_port: "{{ vault_gdav_port }}"
gdav_server_name_external: "{{ vault_gdav_server_name_external }}"
ha_dhparam: "{{ vault_ha_dhparam }}"
ha_dhparam_file: "{{ vault_ha_dhparam_file }}"
ha_mal_beginnings: "{{ vault_ha_mal_beginnings }}"
ha_mal_endings: "{{ vault_ha_mal_endings }}"
ha_mal_host_doms: "{{ vault_ha_mal_host_doms }}"
ha_mal_query_substrings: "{{ vault_ha_mal_query_substrings }}"
ha_mal_substrings: "{{ vault_ha_mal_substrings }}"
ha_stats_users: "{{ vault_ha_stats_users }}"
health_check_port_dovecot: "{{ vault_health_check_port_dovecot }}"
health_check_port_haproxy: "{{ vault_health_check_port_haproxy }}"
health_check_port_postfix: "{{ vault_health_check_port_postfix }}"
http_port: "{{ vault_http_port }}"
https_port: "{{ vault_https_port }}"
imap_port: "{{ vault_imap_port }}"
instance_v4address: "{{ ansible_facts['default_ipv4']['address'] }}"
instance_fqdn: "{{ ansible_facts['fqdn'] }}"
instance_hostname: "{{ ansible_facts['hostname'] }}"
internal_relay_port: "{{ vault_internal_relay_port }}"
lmtp_port: "{{ vault_lmtp_port }}"
local_freshclam_mirror: "{{ vault_local_freshclam_mirror }}"
mail_groupware_users: "{{ vault_mail_groupware_users }}"
mail_local_destinations: "{{ default_mail_local_destinations }}"
mailbox_server_address: "{{ ipaddrs['v4addr']['imapldev'] }}"
mailbox_server_fqdn: "{{ hostvars['imapldev.ldev']['ansible_facts']['fqdn'] }}"
opendkim_private_key: "{{ vault_opendkim_private_key | default(None) }}"
postfix_mua_authorized_xclient_hosts: "{{ ipaddrs['v4addr']['imapldev'] }} [{{ ipaddrs['v6addr']['imapldev'] }}]"
private_ca_cert_certificate: "{{ vault_private_ca_cert_certificate }}"
private_ca_cert_file: "{{ vault_private_ca_cert_file }}"
private_client_cert_cert_content: "{{ host_private_client_cert_cert_content }}"
private_client_cert_cert_file: "{{ host_private_client_cert_cert_file }}"
private_client_cert_key_content: "{{ host_private_client_cert_key_content }}"
private_client_cert_key_file: "{{ host_private_client_cert_key_file }}"
private_client_cert_full_file: "{{ host_private_client_cert_cert_file | replace('-cert', '-full') | default(None) }}"
private_cert_content: "{{ host_private_client_content }}"
private_cert_cert_file: "{{ host_private_cert_cert_file }}"
private_cert_full_file: "{{ host_private_client_cert_full_file | replace('-cert', '-full') | default(None) }}"
private_cert_key_content: "{{ host_private_cert_key_content }}"
private_cert_key_file: "{{ host_private_cert_key_file }}"
public_cert_cert_file: "{{ host_public_cert_cert_file }}"
public_cert_cert_file_src: "{{ host_public_cert_cert_file_src }}"
public_cert_full_file: "{{ host_public_cert_full_file }}"
public_cert_key_file: "{{ host_public_cert_key_file }}"
public_cert_key_file_src: "{{ host_public_cert_key_file_src }}"
public_cert_key_private_key: "{{ host_public_cert_private_key }}"
remote_admin_ip: "{{ vault_remote_admin_ip }}"
remote_ignore_ips: "{{ remote_admin_ip }}{% if remote_monitoring_ips is defined %} {{ remote_monitoring_ips }}{% endif %}"
remote_monitoring_ips: "{{ vault_remote_monitoring_ips }}"
sieve_port: "{{ vault_sieve_port }}"
smtp_port: "{{ vault_smtp_port }}"
smtpd_dh_param: "{{ vault_smtpd_dh_param }}"
smtpd_dh_param_file: "{{ vault_smtpd_dh_param_file }}"
sogo_encryption_key: "{{ vault_sogo_encryption_key }}"
sogodb_password: "{{ vault_sogodb_password }}"
submission_port: "{{ vault_submission_port }}"
submission_relay_host: "{{ hostvars['imapldev.ldev']['ansible_facts']['fqdn'] }}"
submission_relay_port: "{{ vault_submission_relay_port }}"
v4nat_net: "{{ ansible_facts['default_ipv4']['network'] }}"
v4nat_prefix: "{{ ansible_facts['default_ipv4']['prefix'] }}"
v6nat_net: "{{ ansible_facts['default_ipv6']['address'] }}"
v6nat_prefix: "{{ ansible_facts['default_ipv6']['prefix'] }}"
v6natnet_ula: "{{ vault_v6natnet_ula }}"
virtual_alias_domains: "{{ mail_groupware_users | selectattr('alias_domains', 'defined') | map(attribute='alias_domains') | unique | difference(virtual_mailbox_domains) | unique }}"
virtual_alias_domains_hosts: "{{ ([groups['all'] | map('extract', hostvars, 'ansible_facts') | reject('eq', {}) | map(attribute='fqdn'), hostvars | dict2items | map(attribute='key')] | flatten(levels=1)) | unique | difference([virtual_alias_domains, virtual_mailbox_domains] | flatten | unique) }}"
virtual_mailbox_domains: "{{ mail_groupware_users | map(attribute='maildomain') | unique }}"
webhosts_add_www: "{{ vault_webhosts_add_www }}"
webhosts_noadd_www: "{{ vault_webhosts_noadd_www }}"
websites_static: "{{ vault_websites_static }}"
www_port: "{{ vault_wwww_port }}"
ipaddrs:
  v4addr:
    gateldev: "{{ hostvars['gateldev.ldev']['ansible_facts']['default_ipv4']['address'] }}"
    gdavldev: "{{ hostvars['gdavldev.ldev']['ansible_facts']['default_ipv4']['address'] }}"
    imapldev: "{{ hostvars['imapldev.ldev']['ansible_facts']['default_ipv4']['address'] }}"
    smtp01ldev: "{{ hostvars['smtp01ldev.ldev']['ansible_facts']['default_ipv4']['address'] }}"
  v6addr:
    gateldev: "{{ hostvars['gateldev.ldev']['ansible_facts']['default_ipv6']['address'] }}"
    gdavldev: "{{ hostvars['gdavldev.ldev']['ansible_facts']['default_ipv6']['address'] }}"
    imapldev: "{{ hostvars['imapldev.ldev']['ansible_facts']['default_ipv6']['address'] }}"
    smtp01ldev: "{{ hostvars['smtp01ldev.ldev']['ansible_facts']['default_ipv6']['address'] }}"
well_known_admin_aliases: "{{ vault_well_known_admin_aliases }}"
...
