---
- name: Ensure postgres user exists
  become: yes
  ansible.builtin.user:
    name: postgres
    comment: PostgreSQL administrator,,,
    create_home: false
    home: /var/lib/postgresql
    password_lock: true
    shell: /bin/bash
    system: true
- name: Ensure postgresql top-level data dir has the mode and ownership
  become: yes
  notify: Restart PostgreSQL
  ansible.builtin.file:
    path: /var/lib/postgresql/13
    group: postgres
    mode: "0700"
    owner: postgres
    state: directory
- name: Ensure postgresql data dir has the correct ownership and mode
  become: yes
  notify: Restart PostgreSQL
  ansible.builtin.file:
    path: /var/lib/postgresql/13/main
    group: postgres
    mode: "0700"
    owner: postgres
    state: directory
- name: Ensure postgresql ansible dir has the correct ownership
  become: yes
  notify: Restart PostgreSQL
  ansible.builtin.file:
    path: /var/lib/postgresql/.ansible
    group: postgres
    owner: postgres
    recurse: true
    state: directory
- name: Install postgresql
  become: yes
  ansible.builtin.apt:
    name:
    - postgresql
- name: Allow access to databases
  become: yes
  notify: Restart PostgreSQL
  community.postgresql.postgresql_pg_hba:
    address: "{{ item.address }}"
    contype: host
    databases: "{{ item.database }}"
    dest: /etc/postgresql/13/main/pg_hba.conf
    state: present
    users: "{{ item.users }}"
  loop: "{{ postgres_host_access_list }}"
- name: Store etc config so reinstall with existing database works
  become: yes
  ansible.builtin.copy:
    dest: /var/lib/postgresql/13/main/
    force: true
    local_follow: false
    mode: "0700"
    remote_src: true
    src: /etc/postgresql/13/main/
...
